"""pending placeholder unique index

Revision ID: 119948e71831
Revises: ff5742cfcfcd
Create Date: 2026-06-03 00:54:48.614925

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "119948e71831"
down_revision: Union[str, Sequence[str], None] = "ff5742cfcfcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_users_pending_placeholder_username",
        "users",
        ["username"],
        unique=True,
        postgresql_where=sa.text("telegram_user_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_users_pending_placeholder_username",
        table_name="users",
        postgresql_where=sa.text("telegram_user_id IS NULL"),
    )
    # ### end Alembic commands ###
