"""add voided columns to settlements

Revision ID: d282f0443da3
Revises: f8f08c759a68
Create Date: 2026-06-13 01:17:52.327075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d282f0443da3"
down_revision: Union[str, Sequence[str], None] = "f8f08c759a68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settlements", sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("settlements", sa.Column("voided_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_settlements_voided_by_users"),
        "settlements",
        "users",
        ["voided_by"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_settlements_voided_by_users"), "settlements", type_="foreignkey"
    )
    op.drop_column("settlements", "voided_by")
    op.drop_column("settlements", "voided_at")
    # ### end Alembic commands ###
