"""events: scopes, roster, and event_id tags

Adds the events / event_members tables, the partial "one open event per group"
unique index, and the nullable event_id tags on groups (active_event_id),
expenses, and settlements. Hand-written rather than autogenerated because the
circular groups<->events FK and the partial index are exactly the cases the
autogenerate-staleness trap bites (see CLAUDE.md).

Revision ID: e3a7c1d9b042
Revises: 119948e71831
Create Date: 2026-06-04 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3a7c1d9b042"
down_revision: Union[str, Sequence[str], None] = "119948e71831"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "events",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("default_currency", sa.String(length=3), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "default_currency IS NULL OR LENGTH(default_currency) = 3",
            name=op.f("ck_events_currency_len"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'closed')", name=op.f("ck_events_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_events_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_events_group_id_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    # At most one OPEN event per group (partial unique index).
    op.create_index(
        "uq_events_one_open_per_group",
        "events",
        ["group_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "event_members",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_members_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_event_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("event_id", "user_id", name=op.f("pk_event_members")),
    )
    # event_id tags (nullable; NULL = general/regular tracking). groups gets the
    # circular active_event_id pointer — its column + FK are added here, after
    # events exists.
    op.add_column("groups", sa.Column("active_event_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_groups_active_event_id_events"),
        "groups",
        "events",
        ["active_event_id"],
        ["id"],
    )
    op.add_column("expenses", sa.Column("event_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_expenses_event_id_events"),
        "expenses",
        "events",
        ["event_id"],
        ["id"],
    )
    op.add_column("settlements", sa.Column("event_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_settlements_event_id_events"),
        "settlements",
        "events",
        ["event_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        op.f("fk_settlements_event_id_events"), "settlements", type_="foreignkey"
    )
    op.drop_column("settlements", "event_id")
    op.drop_constraint(
        op.f("fk_expenses_event_id_events"), "expenses", type_="foreignkey"
    )
    op.drop_column("expenses", "event_id")
    op.drop_constraint(
        op.f("fk_groups_active_event_id_events"), "groups", type_="foreignkey"
    )
    op.drop_column("groups", "active_event_id")
    op.drop_table("event_members")
    op.drop_index(
        "uq_events_one_open_per_group",
        table_name="events",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_table("events")
