"""groups.bot_is_admin

Revision ID: f8f08c759a68
Revises: e3a7c1d9b042
Create Date: 2026-06-05 01:45:46.395697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f8f08c759a68"
down_revision: Union[str, Sequence[str], None] = "e3a7c1d9b042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with a server_default so existing rows backfill to false, then drop it
    # to match the ORM (Python-side default only) and keep env.py's
    # compare_server_default check clean.
    op.add_column(
        "groups",
        sa.Column(
            "bot_is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("groups", "bot_is_admin", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "bot_is_admin")
    # ### end Alembic commands ###
