"""initial schema

Revision ID: ff5742cfcfcd
Revises:
Create Date: 2026-06-01 09:28:49.370376

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff5742cfcfcd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("group_name", sa.String(length=255), nullable=True),
        sa.Column("default_currency", sa.String(length=3), nullable=False),
        sa.Column("simplify_debts", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "LENGTH(default_currency) = 3", name=op.f("ck_groups_default_currency_len")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint("telegram_chat_id", name=op.f("uq_groups_telegram_chat_id")),
    )
    op.create_table(
        "users",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_table(
        "expenses",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("payer_id", sa.UUID(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("LENGTH(currency) = 3", name=op.f("ck_expenses_currency_len")),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_expenses_amount_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_expenses_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_expenses_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["payer_id"], ["users.id"], name=op.f("fk_expenses_payer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["voided_by"], ["users.id"], name=op.f("fk_expenses_voided_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
    )
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_group_members_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_group_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", "joined_at", name=op.f("pk_group_members")),
    )
    op.create_table(
        "settlements",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("from_user_id", sa.UUID(), nullable=False),
        sa.Column("to_user_id", sa.UUID(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("LENGTH(currency) = 3", name=op.f("ck_settlements_currency_len")),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_settlements_amount_positive")),
        sa.CheckConstraint(
            "from_user_id <> to_user_id", name=op.f("ck_settlements_different_users")
        ),
        sa.ForeignKeyConstraint(
            ["from_user_id"], ["users.id"], name=op.f("fk_settlements_from_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_settlements_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"], ["users.id"], name=op.f("fk_settlements_to_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlements")),
    )
    op.create_table(
        "expense_shares",
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("share_cents", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("share_cents >= 0", name=op.f("ck_expense_shares_nonneg")),
        sa.ForeignKeyConstraint(
            ["expense_id"], ["expenses.id"], name=op.f("fk_expense_shares_expense_id_expenses")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_expense_shares_user_id_users")
        ),
        sa.PrimaryKeyConstraint("expense_id", "user_id", name=op.f("pk_expense_shares")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expense_shares")
    op.drop_table("settlements")
    op.drop_table("group_members")
    op.drop_table("expenses")
    op.drop_table("users")
    op.drop_table("groups")
    # ### end Alembic commands ###
